### ISSUE TITLE
=app-emulation/lxd-0.16: The ebuild phase 'postinst' has exited unexpectedly.

### ISSUE THREAD

**Issue by alunduil** [alunduil/alunduil-overlay#23]
@erikmack,

Looks like the automagic configuration in postinst doesn't gracefully handle failure scenarios.  You can reproduce quite quickly by running etest against the ebuild.  When it's unable to add a bridge device it doesn't know what to do.  Should that kill the ebuild installation or fail in a better way?

**Comment by erikmack** [comment]
> Looks like the automagic configuration in postinst doesn't gracefully handle failure scenarios.  You can reproduce quite quickly by running etest against the ebuild.  When it's unable to add a bridge device it doesn't know what to do.  Should that kill the ebuild installation or fail in a better way?

A PR is entered.

The culprit was actually an "exit" from a function where I wanted
"return".  I also beefed up the error handling around the bridge
addition and caught a sandbox violation.

etest should succeed for you, or at least I have four passing
permutations currently (still running).

BTW, I think --verbose should be the default for etest, since the output
is much more useful but only slightly more lengthy.

Also, I can only realistically run etest with --fast.  My dev laptop is
slightly underpowered (core i5, four cores) and waiting for a full etest
run to see any errors can easily take 24 hours.  I get that --fast is
for devs who are iterating and non--fast is for CI tools, but consider
whether --fast should be a default.

Also, a --help would be welcome.

Take care,
-- 
Erik Mackdanz

**Comment by alunduil** [comment]
I've thought about making verbose and fast default parameters.  I've been following the nose pattern which assumes that you should specifically ask for it to short circuit and be noisy.  I always run etest with verbose, fast, and jobs set to three.  etest does have a --help and it works as well.  If it's not working for you we should troubleshoot that as an issue in etest.

**Comment by alunduil** [comment]
Closing this as the project is currently abandoned.
